#!/usr/bin/env python3
# Generates base/screens/weather.yaml (the Weather carousel screen, base id 5).
#   python scripts/gen_weather.py
#
# Modern look: fixed partly-cloudy palette, colour-coded centre temperature, ANIMATED condition
# icons (animimg frame loops, every HA condition maps to one of 7 icons), and a glow that slides
# around the rim to the selected day. Self-contained: it owns the HA forecast data layer (sensors +
# parsing into g_wx_*) AND the rendering. Animated frames: assets/sprites/weather/<key>0..7.png.
#
# DATA layer (sensors/parser/globals) is kept as raw strings; the modern render/page is an f-string.
import os

ICONS = ["sun", "partly", "moon", "cloud", "rain", "storm", "snow"]
NF = 8
DUR = "1400ms"
BASE = "https://raw.githubusercontent.com/h3ll5ur7er/dialscreen/main/assets/sprites/weather/"
BG = "0x1C2838"; GLOW = "0xCAD6E8"; RIM = "0xDCE6F2"; ACCENT = "0x9AA6B2"; CONDC = "0xCFE0F2"; PAGE = "0x0B1020"
RING = "0x33455C"   # faint outer ring that traces the bezel

# ---------- data layer (raw - HA sensors + forecast parser + data globals + font) ----------
HEAD = """# Weather - carousel screen (base id 5). GENERATED by scripts/gen_weather.py.
# A dial of forecast days around the rim (knob scrolls), animated condition icon + colour-coded
# temperature in the centre, a glow that slides to the selected day. Forecast comes from a Home
# Assistant helper sensor (see base/screens/weather.ha-helper.yaml). Remove: drop from `files:`.

esphome:
  on_boot:
    - priority: 655
      then:
        - lambda: 'id(g_present)[5] = true;'
    - priority: 650
      then:
        - lambda: |-
            int g = id(g_wgrp_n)++;
            id(g_wgrp_labels) += (g ? "\\n" : ""); id(g_wgrp_labels) += "Weather";
            int o = id(g_wopt_n)++;
            id(g_wopt_group)[o] = g; id(g_wopt_label)[o] = "Fahrenheit"; id(g_wopt_kind)[o] = 0; id(g_wopt_ptr)[o] = &id(g_wx_fahrenheit);

globals:
  # --- forecast data ---
  - id: g_wx_fahrenheit
    type: bool
    restore_value: yes
    initial_value: 'false'
  - id: g_wx_now
    type: int
    restore_value: no
    initial_value: '-127'
  - id: g_wx_state_cur
    type: std::string
    restore_value: no
  - id: g_wx_cond
    type: std::string[7]
    restore_value: no
  - id: g_wx_icon
    type: std::string[7]
    restore_value: no
  - id: g_wx_name
    type: std::string[7]
    restore_value: no
  - id: g_wx_hi
    type: int[7]
    restore_value: no
  - id: g_wx_lo
    type: int[7]
    restore_value: no
  - id: g_wx_n
    type: int
    restore_value: no
    initial_value: '0'
  - id: g_wx_day
    type: int
    restore_value: no
    initial_value: '0'
  # --- render cache ---
  - id: g_wx_sel
    type: std::string
    restore_value: no
  - id: g_wx_tc
    type: int
    restore_value: no
    initial_value: '-127'
  - id: g_wx_lastcond
    type: std::string
    restore_value: no
  - id: g_wx_ikey
    type: std::string
    restore_value: no
  - id: g_wx_gpos
    type: float
    restore_value: no
    initial_value: '0.0'

font:
  - file: "https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf"
    id: icons_wx
    size: 30
    bpp: 4
    glyphs: ["\U000f0599", "\U000f0594", "\U000f0595", "\U000f0591", "\U000f059d", "\U000f0593", "\U000f0596", "\U000f0597", "\U000f0598", "\U000f0590"]
"""

SENSORS = """
sensor:
  - platform: homeassistant
    id: wx_now_temp
    entity_id: ${weather_entity}
    attribute: temperature
    on_value:
      - lambda: 'id(g_wx_now) = (int) roundf(x);'
      - script.execute: wx_render

text_sensor:
  - platform: homeassistant
    id: wx_now_state
    entity_id: ${weather_entity}
    on_value:
      - lambda: 'id(g_wx_state_cur) = x;'
      - script.execute: wx_render
  - platform: homeassistant
    id: wx_week
    entity_id: ${forecast_entity}
    on_value:
      - lambda: |-
          auto glyph = [](const std::string &s) -> std::string {
            if (s == "sunny") return std::string("\U000f0599");
            if (s == "clear-night") return std::string("\U000f0594");
            if (s == "partlycloudy") return std::string("\U000f0595");
            if (s == "fog") return std::string("\U000f0591");
            if (s == "windy" || s == "windy-variant") return std::string("\U000f059d");
            if (s == "lightning" || s == "lightning-rainy") return std::string("\U000f0593");
            if (s == "pouring") return std::string("\U000f0596");
            if (s == "rainy") return std::string("\U000f0597");
            if (s == "snowy" || s == "snowy-rainy" || s == "hail") return std::string("\U000f0598");
            return std::string("\U000f0590");
          };
          std::string s = x;
          for (int i = 0; i < 7; i++) { id(g_wx_icon)[i] = ""; id(g_wx_cond)[i] = ""; }
          int n = 0; size_t pos = 0;
          while (n < 7) {
            size_t bar = s.find('|', pos);
            std::string seg = (bar == std::string::npos) ? s.substr(pos) : s.substr(pos, bar - pos);
            size_t c1 = seg.find(',');
            if (c1 != std::string::npos) {
              size_t c2 = seg.find(',', c1 + 1);
              size_t c3 = (c2 != std::string::npos) ? seg.find(',', c2 + 1) : std::string::npos;
              if (c2 != std::string::npos && c3 != std::string::npos) {
                std::string cond = seg.substr(0, c1);
                id(g_wx_cond)[n] = cond;
                id(g_wx_icon)[n] = glyph(cond);
                id(g_wx_hi)[n] = atoi(seg.substr(c1 + 1, c2 - c1 - 1).c_str());
                id(g_wx_lo)[n] = atoi(seg.substr(c2 + 1, c3 - c2 - 1).c_str());
                id(g_wx_name)[n] = seg.substr(c3 + 1);
                n++;
              }
            }
            if (bar == std::string::npos) break;
            pos = bar + 1;
          }
          id(g_wx_n) = n;
          if (id(g_wx_day) >= n) id(g_wx_day) = 0;
      - script.execute: wx_render
"""


def image_block():
    return "\n".join(
f"""  - platform: file
    id: img_wx_{k}{i}
    file: "{BASE}{k}{i}.png"
    type: RGB565
    transparency: alpha_channel""" for k in ICONS for i in range(NF))


def animimg_widgets():
    out = []
    for k in ICONS:
        src = ", ".join(f"img_wx_{k}{i}" for i in range(NF))
        out.append(
            f"        - animimg: {{ id: wx_a_{k}, align: CENTER, x: 0, y: -52, duration: {DUR}, "
            f"repeat_count: 65535, auto_start: false, hidden: true, src: [ {src} ] }}")
    return "\n".join(out)


def dispatch_stop_hide():
    out = [f"            - lvgl.animimg.stop: wx_a_{k}" for k in ICONS]
    out += [f"            - lvgl.widget.hide: wx_a_{k}" for k in ICONS]
    return "\n".join(out)


def dispatch_show():
    return "\n".join(
        f"            - if: {{ condition: {{ lambda: 'return id(g_wx_ikey) == \"{k}\";' }}, "
        f"then: [ lvgl.widget.show: wx_a_{k}, lvgl.animimg.start: wx_a_{k} ] }}"
        for k in ICONS)


def rim_updates():
    out = []
    for i in range(7):
        out.append(
            f"      - lvgl.widget.update: {{ id: wx_d{i}, hidden: !lambda 'return {i} >= id(g_wx_n);', "
            f"x: !lambda 'int n=id(g_wx_n); if(n<1)n=1; return (int) lroundf(140.0f * sinf({i} * 6.2831853f / n));', "
            f"y: !lambda 'int n=id(g_wx_n); if(n<1)n=1; return (int) lroundf(-140.0f * cosf({i} * 6.2831853f / n));' }}")
        out.append(
            f"      - lvgl.label.update:  {{ id: wx_d{i}, text: !lambda 'return id(g_wx_n) > {i} ? id(g_wx_icon)[{i}] : std::string(\"\");' }}")
    return "\n".join(out)


def rim_widgets():
    return "\n".join(
        f"        - label: {{ id: wx_d{i}, align: CENTER, x: 0, y: 0, text: \"\", text_font: icons_wx, text_color: {RIM}, hidden: true }}"
        for i in range(7))


MODERN = f"""
image:
{image_block()}

script:
  - id: wx_render
    then:
      - lambda: |-
          int d = id(g_wx_day);
          bool has = (id(g_wx_n) > 0 && d < id(g_wx_n));
          id(g_wx_sel) = has ? id(g_wx_cond)[d] : id(g_wx_state_cur);
          id(g_wx_tc)  = has ? id(g_wx_hi)[d] : id(g_wx_now);
      - lvgl.label.update:
          id: wx_day
          text: !lambda |-
            int d = id(g_wx_day);
            if (id(g_wx_n) <= 0 || d >= id(g_wx_n)) return std::string("TODAY");
            std::string s = id(g_wx_name)[d];
            if (s == "Mon") return std::string("MONDAY");
            if (s == "Tue") return std::string("TUESDAY");
            if (s == "Wed") return std::string("WEDNESDAY");
            if (s == "Thu") return std::string("THURSDAY");
            if (s == "Fri") return std::string("FRIDAY");
            if (s == "Sat") return std::string("SATURDAY");
            if (s == "Sun") return std::string("SUNDAY");
            return s;
      - lvgl.label.update:
          id: wx_htemp
          text: !lambda |-
            int d = id(g_wx_day);
            bool f = id(g_wx_fahrenheit);
            char u = f ? 'F' : 'C';
            if (id(g_wx_n) <= 0 || d >= id(g_wx_n)) {{
              if (id(g_wx_now) > -100) {{ int n = id(g_wx_now); if (f) n = n*9/5+32; char b[12]; snprintf(b,sizeof(b),"%d°%c",n,u); return std::string(b); }}
              return std::string("--");
            }}
            int hi = id(g_wx_hi)[d], lo = id(g_wx_lo)[d];
            if (f) {{ hi = hi*9/5+32; lo = lo*9/5+32; }}
            char b[24]; snprintf(b,sizeof(b),"%d° / %d°",hi,lo); return std::string(b);
      - lvgl.label.update:
          id: wx_cond
          text: !lambda |-
            if (id(g_wx_n) <= 0) return std::string("Add the HA forecast helper");
            std::string s = id(g_wx_sel);
            if (s == "sunny") return std::string("Sunny");
            if (s == "clear-night") return std::string("Clear");
            if (s == "partlycloudy") return std::string("Partly Cloudy");
            if (s == "cloudy") return std::string("Cloudy");
            if (s == "fog") return std::string("Fog");
            if (s == "rainy") return std::string("Rainy");
            if (s == "pouring") return std::string("Heavy Rain");
            if (s == "lightning" || s == "lightning-rainy") return std::string("Storm");
            if (s == "snowy" || s == "snowy-rainy") return std::string("Snow");
            if (s == "hail") return std::string("Hail");
            if (s == "windy" || s == "windy-variant") return std::string("Windy");
            if (s == "exceptional") return std::string("Severe");
            return s;
      - if:
          condition: {{ lambda: 'return id(g_wx_sel) != id(g_wx_lastcond);' }}
          then:
            - lambda: |-
                id(g_wx_lastcond) = id(g_wx_sel);
                std::string s = id(g_wx_sel), k;
                if (s == "sunny") k = "sun";
                else if (s == "clear-night") k = "moon";
                else if (s == "partlycloudy") k = "partly";
                else if (s == "rainy" || s == "pouring") k = "rain";
                else if (s == "lightning" || s == "lightning-rainy") k = "storm";
                else if (s == "snowy" || s == "snowy-rainy" || s == "hail") k = "snow";
                else k = "cloud";
                id(g_wx_ikey) = k;
{dispatch_stop_hide()}
{dispatch_show()}
      - lvgl.widget.update: {{ id: wx_glow, hidden: !lambda 'return id(g_wx_n) <= 0;' }}
{rim_updates()}
      - lvgl.label.update: {{ id: wx_htemp, text_color: 0xFFFFFF }}
      - if: {{ condition: {{ lambda: 'return id(g_wx_tc) > -100 && id(g_wx_tc) <= 0;' }},  then: [ lvgl.label.update: {{ id: wx_htemp, text_color: 0x7FB2FF }} ] }}
      - if: {{ condition: {{ lambda: 'return id(g_wx_tc) > 0 && id(g_wx_tc) < 10;' }},     then: [ lvgl.label.update: {{ id: wx_htemp, text_color: 0x6FD0E8 }} ] }}
      - if: {{ condition: {{ lambda: 'return id(g_wx_tc) >= 10 && id(g_wx_tc) < 18;' }},   then: [ lvgl.label.update: {{ id: wx_htemp, text_color: 0x7FE6B0 }} ] }}
      - if: {{ condition: {{ lambda: 'return id(g_wx_tc) >= 18 && id(g_wx_tc) < 25;' }},   then: [ lvgl.label.update: {{ id: wx_htemp, text_color: 0xFFD061 }} ] }}
      - if: {{ condition: {{ lambda: 'return id(g_wx_tc) >= 25;' }},                       then: [ lvgl.label.update: {{ id: wx_htemp, text_color: 0xFF7A4D }} ] }}
{SENSORS}
interval:
  - interval: 50ms
    then:
      - if:
          condition: {{ lambda: 'return id(g_nav_req) && id(g_base)==5;' }}
          then:
            - lambda: 'id(g_nav_req) = false; id(g_knob_capture) = true; id(g_wx_day) = 0; id(g_wx_gpos) = 0.0f; id(g_wx_lastcond) = "";'
            - if: {{ condition: {{ lambda: 'return id(g_nav_anim)==0;' }}, then: [lvgl.page.show: {{ id: page_weather, animation: move_left,   time: 250ms }}] }}
            - if: {{ condition: {{ lambda: 'return id(g_nav_anim)==1;' }}, then: [lvgl.page.show: {{ id: page_weather, animation: move_right,  time: 250ms }}] }}
            - if: {{ condition: {{ lambda: 'return id(g_nav_anim)==2;' }}, then: [lvgl.page.show: {{ id: page_weather, animation: move_top,    time: 250ms }}] }}
            - if: {{ condition: {{ lambda: 'return id(g_nav_anim)==3;' }}, then: [lvgl.page.show: {{ id: page_weather, animation: move_bottom, time: 250ms }}] }}
            - script.execute: wx_render
  - interval: 120ms
    then:
      - if:
          condition: {{ lambda: 'return id(g_base)==5 && id(g_knob_delta) != 0;' }}
          then:
            - lambda: |-
                id(g_wx_day) += id(g_knob_delta); id(g_knob_delta) = 0;
                int mx = (id(g_wx_n) > 0) ? id(g_wx_n) - 1 : 0;
                if (id(g_wx_day) < 0) id(g_wx_day) = 0;
                if (id(g_wx_day) > mx) id(g_wx_day) = mx;
            - script.execute: wx_render
  - interval: 30ms
    then:
      - if:
          condition: {{ lambda: 'return id(g_base)==5;' }}
          then:
            - lambda: |-
                float p = id(g_wx_gpos), tgt = (float) id(g_wx_day);
                if (fabsf(tgt - p) > 0.001f) {{                 // only while actually sliding
                  int n = id(g_wx_n); if (n < 1) n = 1;
                  p += (tgt - p) * 0.35f;
                  if (fabsf(tgt - p) < 0.02f) p = tgt;
                  id(g_wx_gpos) = p;
                  float rx = 140.0f * sinf(p * 6.2831853f / n);
                  float ry = -140.0f * cosf(p * 6.2831853f / n);
                  lv_obj_set_pos(id(wx_glow), 180 + (int) lroundf(rx) - 28, 180 + (int) lroundf(ry) - 28);
                }}

lvgl:
  pages:
    - id: page_weather
      bg_color: {PAGE}
      widgets:
        - obj: {{ id: wx_bg, align: CENTER, x: 0, y: 0, width: 360, height: 360, radius: 0, bg_color: {BG}, bg_opa: COVER, border_width: 0 }}
        - obj: {{ id: wx_ring_out, align: CENTER, width: 348, height: 348, radius: 174, bg_opa: TRANSP, border_width: 2, border_color: {RING}, border_opa: 55%, clickable: false, scrollable: false }}
        - obj: {{ id: wx_glow, x: 152, y: 12, width: 56, height: 56, radius: 28, bg_color: {GLOW}, bg_opa: 30%, border_width: 0, hidden: true }}
{rim_widgets()}
{animimg_widgets()}
        - label: {{ id: wx_day, align: CENTER, x: 0, y: -10, text: "", text_font: font_artist, text_color: {ACCENT} }}
        - label: {{ id: wx_htemp, align: CENTER, x: 0, y: 24, text: "--", text_font: montserrat_34, text_color: 0xFFFFFF }}
        - label: {{ id: wx_cond, align: CENTER, x: 0, y: 62, text: "", text_font: font_med, text_color: {CONDC} }}
"""

YAML = HEAD + MODERN

here = os.path.dirname(os.path.abspath(__file__))
out = os.path.normpath(os.path.join(here, "..", "base", "screens", "weather.yaml"))
with open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write(YAML)
print("wrote", out, "(", len(YAML), "bytes )")
